services:
  wordpress:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    ports:
      - ${HOST_DEV_PORT_APP}:80
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_DEBUG: 1
    volumes:
      - wordpress:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins
      - ./themes:/var/www/html/wp-content/themes
      - ./uploads:/var/www/html/wp-content/uploads

  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - ${HOST_DEV_PORT_DB}:3306

volumes:
  mariadb:
  wordpress:
